manifest: set hal version to 2
When the device manifest target-level is to 7 (Android 13), the
compatibility matrix expect light HAL version set to 2.

Otherwise we have the following errors:
```
The following HALs in device manifest are not declared in FCM <= level 7:
  android.hardware.light.ILights/default (@1)
ERROR: files are incompatible: The following instances are in the device manifest but not specified in framework compatibility matrix:
    android.hardware.light.ILights/default (@1)
```

Signed-off-by: Julien Masson <jmasson@baylibre.com>